name:                transitive-anns
version:             0.1.0.0
github:              "isovector/transitive-anns"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "Sandy Maguire"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/transitive-anns#readme>

dependencies:
- base >= 4.7 && < 5
- ghc
- ghc-tcplugins-extra
- syb
- containers
- hspec
- monoidal-containers

default-extensions:
  - AllowAmbiguousTypes
  - DataKinds
  - FlexibleContexts
  - ScopedTypeVariables
  - TypeApplications
  - KindSignatures

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=TransitiveAnns.Plugin
    - -fno-warn-redundant-constraints
    - -dcore-lint
    build-tools:
    - hspec-discover >= 2.0
    dependencies:
    - transitive-anns
    - hspec

